### ISSUE TITLE
On checking the verified box window should be reloaded.

### ISSUE THREAD

**Issue by Ary0405** [Ary0405/cl-admin-portal#2]
After checking verified box window should reload but after updating the database. If window.location.reload() is used, window is reloaded before updating of data.
Need a fix for that.

**Comment by sujith-rek** [comment]
@Ary0405  
After every submission we reload, it'll need to be updated and fetching and everything need to be done
which takes soo much time

so I'm thinking, we will ask to check the boxes as much as they can and just reload
